### PR TITLE
Webview - Visit initial web address, go back, forward, home

### PR DESCRIPTION
**Pull request by SuaYoo**
https://github.com/ukwa/npld-player/issues/7, https://github.com/ukwa/npld-player/issues/5 Enables users to go back, forward, and home from initially visited web address.

### Manual testing
1. Prerequisite:
  a. Create `.env` file from `sample.env` (`cp sample.env .env`)
  b. Run `yarn` to install new dependencies
  c. Run `yarn start` to open app
1. Click links within website. Verify address bar updates as expected
1. Click arrows and home icon to go back/forward/home. Verify app updates as expected
1. Minimize window size until URL is truncated. Verify you're able to focus on the address bar and scroll to the end of the address bar to view the full URL

### Screenshots
Screen Shot 2022-05-06 at 1 32 37 PM

### TODO
- Handle external links/links opened in new window
- Handle prefix/protocol

### CODE REVIEW

**Comment by SuaYoo** [comment]
@ikreymer I have webview navigation working here with plain URLs (i.e. without `WEB_ARCHIVE_PREFIX`) if you can take a look at making those env variables available in the app.

**Comment by ikreymer** [comment]
Looks good! Maybe should `maximize()` the window by default also (can add later).

**Comment by ikreymer** [comment]
Also, perhaps the initial URL should be set in webpack env config?

**Comment by SuaYoo** [comment]
> Also, perhaps the initial URL should be set in webpack env config?

@ikreymer Moved to `.env` file which is loaded in `preload.ts`, could be moved to wherever else makes the most sense in configuring app, too

**Comment by ikreymer** [comment]
> > Also, perhaps the initial URL should be set in webpack env config?
> 
> @ikreymer Moved to `.env` file which is loaded in `preload.ts`, could be moved to wherever else makes the most sense in configuring app, too

Should be good for now, if we don't end up using it for anything else, might be able to just add it to the main load.

**Review by ikreymer — APPROVED** [review]

**Pull request merged**
